import importlib

attack_zoo = {
    # gradient
    'fgsm': ('.gradient.fgsm', 'FGSM'),
    'ifgsm': ('.gradient.ifgsm', 'IFGSM'),
    'mifgsm': ('.gradient.mifgsm', 'MIFGSM'),
    'nifgsm': ('.gradient.nifgsm', 'NIFGSM'),
    'pifgsm': ('.gradient.pifgsm', 'PIFGSM'),
    'vmifgsm': ('.gradient.vmifgsm', 'VMIFGSM'),
    'vnifgsm': ('.gradient.vnifgsm', 'VNIFGSM'),
    'emifgsm': ('.gradient.emifgsm', 'EMIFGSM'),
    'aifgtm': ('.gradient.aifgtm', 'AIFGTM'),
    'ifgssm': ('.gradient.ifgssm', 'IFGSSM'),
    'smifgrm': ('.gradient.smifgrm', 'SMIFGRM'),
    'vaifgsm': ('.gradient.vaifgsm', 'VAIFGSM'),
    'rap': ('.gradient.rap', 'RAP'),
    'pcifgsm': ('.gradient.pcifgsm', 'PCIFGSM'),
    'iefgsm': ('.gradient.iefgsm', 'IEFGSM'),
    'gra': ('.gradient.gra', 'GRA'),
    'gnp': ('.gradient.gnp', 'GNP'),
    'mig': ('.gradient.mig', 'MIG'),
    'dta': ('.gradient.dta', 'DTA'),
    'pgn': ('.gradient.pgn', 'PGN'),
    'mef': ('.gradient.mef', 'MEF'),
    'ggs': ('.gradient.ggs', 'GGS'),
    'eaa': ('.gradient.eaa', 'EAA'),
    'anda': ('.gradient.anda', 'ANDA'),
    'gifgsm': ('.gradient.gifgsm', 'GIFGSM'),
    'rgmifgsm': ('.gradient.mifgsm_with_tricks', 'RGMIFGSM'),
    'dual_mifgsm': ('.gradient.mifgsm_with_tricks', 'DualMIFGSM'),
    'ens_mifgsm': ('.gradient.mifgsm_with_tricks', 'Ens_FGSM_MIFGSM'),
    'fgsra': ('.gradient.fgsra', 'FGSRA'),
    'mumodig': ('.gradient.mumodig','MUMODIG'),
    'gaa': ('.gradient.gaa', 'GAA'),  
    'foolmix': ('.gradient.foolmix', 'Foolmix'),  
    
    # input transformation
    ## Untargeted
    'dim': ('.input_transformation.dim', 'DIM'),
    'tim': ('.input_transformation.tim', 'TIM'),
    'sim': ('.input_transformation.sim', 'SIM'),
    'dem': ('.input_transformation.dem', 'DEM'),
    'admix': ('.input_transformation.admix', 'Admix'),
    'atta': ('.input_transformation.atta', 'ATTA'),
    'maskblock': ('.input_transformation.maskblock', 'MaskBlock'),
    'ssm': ('.input_transformation.ssm', 'SSM'),
    'aitl': ('.input_transformation.aitl', 'AITL'),
    'pam': ('.input_transformation.pam', 'PAM'),
    'lpm': ('.input_transformation.lpm', 'LPM'),
    'sia': ('.input_transformation.sia', 'SIA'),
    'sid': ('.input_transformation.sid', 'SID'),
    'ic': ('.input_transformation.ic', 'IC'),
    'gs': ('.input_transformation.gs', 'GS'),
    'stm': ('.input_transformation.stm', 'STM'),
    'usmm': ('.input_transformation.usmm', 'USMM'),
    'decowa': ('.input_transformation.decowa', 'DeCowA'),
    'decowa1': ('.input_transformation.decowa1', 'DeCowABM'),
    'decowa4': ('.input_transformation.decowa4', 'DeCowABM'),
    'decowa5': ('.input_transformation.decowa5', 'DeCowABM'),
    'decowa6': ('.input_transformation.decowa6', 'DeCowABM'),
    'decowa7': ('.input_transformation.decowa7', 'DeCowABM'),
    'decowa8': ('.input_transformation.decowa8', 'DeCowABM'),
    'decowa9': ('.input_transformation.decowa9', 'DeCowABM'),
    'decowa10': ('.input_transformation.decowa10', 'DeCowABM'),
    'decowa11': ('.input_transformation.decowa11', 'DeCowABM'),
    'decowa12': ('.input_transformation.decowa12', 'DeCowABM'),
    'decowa13': ('.input_transformation.decowa13', 'DeCowABM'),
    'decowa14': ('.input_transformation.decowa14', 'DeCowABM'),
    'decowa15': ('.input_transformation.decowa15', 'DeCowABM'),
    'decowa16': ('.input_transformation.decowa16', 'DeCowABM'),
    'decowa161': ('.input_transformation.decowa161', 'DeCowABM'),
    'decowa16_vmifgsm': ('.input_transformation.decowa16_vmifgsm', 'DeCowABM'),
    'decowa16_emifgsm': ('.input_transformation.decowa16_emifgsm', 'DeCowABM'),
    'decowa16_gra': ('.input_transformation.decowa16_gra', 'DeCowABM'),
    'decowa16_pgn': ('.input_transformation.decowa16_pgn', 'DeCowABM'),
    'decowa16_mef': ('.input_transformation.decowa16_mef', 'DeCowABM'),
    'decowa16_gaa': ('.input_transformation.decowa16_gaa', 'DeCowABM'),
    'decowa17': ('.input_transformation.decowa17', 'DeCowABM'),
    'decowa18': ('.input_transformation.decowa18', 'DeCowABM'),
    'decowa19': ('.input_transformation.decowa19', 'DeCowABM'),
    'decowa20': ('.input_transformation.decowa20', 'DeCowABM'),
    'eda': ('.input_transformation.eda', 'EDA'),

    'l2t': ('.input_transformation.l2t', 'L2T'),
    'bsr': ('.input_transformation.bsr', 'BSR'),
    'ops': ('.input_transformation.ops', 'OPS'),
    'bss': ('.input_transformation.bss', 'BSS'),
    ## Targeted
    'odi': ('.input_transformation.odi.odi', 'ODI'),
    'su': ('.input_transformation.su', 'SU'),
    'idaa': ('.input_transformation.idaa', 'IDAA'),
    'ssm_p': ('.input_transformation.ssm_with_tricks', 'SSA_P'),
    'ssm_h': ('.input_transformation.ssm_with_tricks', 'SSM_H'),
    
    # advanced_objective
    ## Untargeted
    'tap': ('.advanced_objective.tap', 'TAP'),
    'ila': ('.advanced_objective.ila', 'ILA'),
    'ata': ('.advanced_objective.ata', 'ATA'),
    'yaila': ('.advanced_objective.yaila.yaila', 'YAILA'),
    'fia': ('.advanced_objective.fia', 'FIA'),
    'ir': ('.advanced_objective.ir', 'IR'),
    'trap': ('.advanced_objective.trap', 'TRAP'),
    'taig': ('.advanced_objective.taig', 'TAIG'),
    'fmaa': ('.advanced_objective.fmaa', 'FMAA'),
    'naa': ('.advanced_objective.naa', 'NAA'),
    'rpa': ('.advanced_objective.rpa', 'RPA'),
    'fuzziness_tuned': ('.advanced_objective.fuzziness_tuned', 'Fuzziness_Tuned'),
    'danaa': ('.advanced_objective.danaa', 'DANAA'),
    'ilpd': ('.advanced_objective.ilpd', 'ILPD'),
    'dsbma': ('.advanced_objective.dsbma', 'DSBMA'),
    'bfa': ('.advanced_objective.bfa', 'BFA'),
    'p2fa': ('.advanced_objective.p2fa', 'P2FA'),
    ## Targeted
    'aa': ('.advanced_objective.aa', 'AA'),
    'potrip': ('.advanced_objective.potrip', 'POTRIP'),
    'logit': ('.advanced_objective.logit', 'LOGIT'),
    'logit_margin': ('.advanced_objective.logit_margin', 'Logit_Margin'),
    'cfm': ('.advanced_objective.cfm', 'CFM'),
    'fft': ('.advanced_objective.fft', 'FFT'),
    
    # model_related
    'sgm': ('.model_related.sgm', 'SGM'),
    'linbp': ('.model_related.linbp', 'LinBP'),
    'pna_patchout': ('.model_related.pna_patchout', 'PNA_PatchOut'),
    'llta': ('.model_related.llta_networks.llta', 'LLTA'),
    'iaa': ('.model_related.iaa', 'IAA'),
    'sapr': ('.model_related.sapr', 'SAPR'),
    'setr': ('.model_related.setr', 'SETR'),
    'ata_vit': ('.model_related.ata_vit', 'ATA_ViT'),
    'dra': ('.model_related.dra', 'DRA'),
    'mta': ('.model_related.mta', 'MTA'),
    'mup': ('.model_related.mup', 'MUP'),
    'tgr': ('.model_related.tgr', 'TGR'),
    'fer': ('.model_related.fer', 'FER'),
    'dsm': ('.model_related.dsm', 'DSM'),
    'dhf': ('.model_related.dhf', 'DHF_MIFGSM'),
    'bpa': ('.model_related.bpa', 'BPA'),
    'ags': ('.model_related.ags', 'AGS'),
    'metassa': ('.model_related.metassa', 'MetaSSA'),
    'vdc': ('.model_related.vdc', 'VDC'),
    'ma': ('.model_related.ma', 'MA'),
    'att': ('.model_related.att', 'ATT'),
    'fpr': ('.model_related.fpr', 'FPR'),
    'awt': ('.model_related.awt', 'AWT'),
    'faug': ('.model_related.faug', 'FAUG'),
    'ana': ('.model_related.ana', 'ANA'),
    'll2s': ('.model_related.ll2s', "LL2S"),

    # ensemble
    'ens': ('.ensemble.ens', 'ENS'),
    'ghost': ('.model_related.ghost', 'GhostNetwork_MIFGSM'),
    'svre': ('.ensemble.svre', 'SVRE'),
    'lgv': ('.ensemble.lgv', 'LGV'),
    'mba': ('.ensemble.mba', 'MBA'),
    'adaea': ('.ensemble.adaea', 'AdaEA'),
    'cwa': ('.ensemble.cwa', 'CWA'),
    'smer': ('.ensemble.smer', 'SMER'),
    ## Targeted
    'sasd_ws': ('.ensemble.sasd_ws', 'SASD_WS'),
    
    # generation
    ## Untargeted
    'cdtp': ('.generation.cdtp', 'CDTP'),
    'ltp': ('.generation.ltp', 'LTP'),
    'ada': ('.generation.ada', 'ADA'),
    'ge_advgan': ('.generation.ge_advgan', 'GE_ADVGAN'),
    'diffattack': ('.generation.diffattack', 'DiffAttack'),
    ## Targeted
    'ttp': ('.generation.ttp', 'TTP'),
    'm3d': ('.generation.m3d', 'M3D'),
    
}


def load_attack_class(attack_name):
    if attack_name not in attack_zoo:
        raise Exception('Unspported attack algorithm {}'.format(attack_name))
    module_path, class_name = attack_zoo[attack_name]
    module = importlib.import_module(module_path, __package__)
    attack_class = getattr(module, class_name)
    return attack_class


__version__ = '1.0.0'
